name: d17
version: 1.6.1
author: Adam Stark <llamadonica@gmail.com>
description: Lightweight dependency injection framework for Dart.
homepage: https://github.com/llamadonica/d17
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  meta: '>=0.8.8 <0.9.0'
dev_dependencies:
  test: any
